config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root to: 'main#index'

  get 'main/index'

  resources :design_reference, only: [:index] do
  	collection do
  	  get :register
    end
  end

  resources :users, only: [:create,:update] 
  get 'signup' => 'users#new', as: :new_user	

  resources :sessions, only: [:create]
  get 'logout' => 'sessions#destroy' 
  get 'login'  => 'sessions#new', as: :new_session

  resources :admin, only: [:index]

  namespace :admin do
    resources :companies
    resources :categories
  end  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user.roles.includes(:permissions).each do |role|
        role.permissions.each do |p|
            can p.action.to_sym, p.klass.constantize, p.condition_hash
        end
        can :manage, :all if role.super_admin?
    end    

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	extend ActsAsTree::TreeView
	acts_as_tree order: 'name'

	extend FriendlyId
    friendly_id :name, use: :slugged

end

app/models/city.rb
class City < ApplicationRecord

	validates :name, :slug , presence: true
	
end

app/models/company.rb
class Company < ApplicationRecord
	extend FriendlyId
	friendly_id :uid, use: :slugged
	attr_accessor :slug

	belongs_to :city

	validates :name, :owner_id , :city_id, :address ,presence: true

	TYPE = { 1 => 'Seller' , 2 => 'Vendor' }
	STATUS = { 1 => 'Active' , 2 => 'InActive', 3 => 'Blocked' }

end

app/models/permission.rb
class Permission < ApplicationRecord

	has_and_belongs_to_many :roles

	serialize :condition , Hash
	
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
	has_and_belongs_to_many :permissions

	def super_admin?
	  uid == 'super_admin'
	end
	
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  delegate :can?, :cannot?, :to => :ability

  has_and_belongs_to_many :roles

  def ability
    @ability ||= Ability.new(self)
  end
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController

	load_and_authorize_resource only: [:edit,:update]

	def index
	  @categories_grid = CategoriesGrid.new(params[:categories_grid]) do |scope|
	    scope.page(params[:page])
	  end
	  add_crumb "Category Managment", admin_categories_path
	end

	def new
	  @category = Category.new
      add_crumb "Create Company", admin_categories_path
	end

	def edit
	  add_crumb "Update Category", admin_categories_path	
	end

	def create
	  @category = Category.new(category_params)
       if @category.save
        redirect_to admin_categories_path, notice: 'Category was successfully created.'
      else
        render :new
      end
	end

	def update
	  if @company.update(company_params)
  	    redirect_to admin_categories_path, notice: 'Category was successfully updated.'
	  else
  		render :edit
	  end
	end

	private

	def category_params
		params.require(:category).permit(:name,:parent_id)
	end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < AdminController
  
  load_and_authorize_resource only: [:edit,:update]
  
  def index
    @companies_grid = CompaniesGrid.new(params[:companies_grid]) do |scope|
      scope.page(params[:page])
    end
    add_crumb "Company Managment", admin_companies_path
  end

  def new
    @company = Company.new
    add_crumb "Create Company", admin_companies_path
  end

  def edit
    add_crumb "Update Company", admin_companies_path
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to admin_companies_path, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to admin_companies_path, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name,:company_type,:city_id,:address,:status,:owner_id)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :require_login
	authorize_resource
	layout 'admin'
	before_action :set_crumb

	def index
	end	

	def set_crumb
    	add_crumb "Admin", admin_index_path
	end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	rescue_from CanCan::AccessDenied do |exception|
		redirect_to main_app.root_url, :alert => exception.message
	end
	
end

app/controllers/design_reference_controller.rb
class DesignReferenceController < ApplicationController
  
  def index
  end

  def register
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
  end

  def create
  	user = login(params[:email], params[:password], true)
    if user.present?
      flash[:success] = "Signed In Successfully"
      redirect_back_or_to root_url
    else
      flash[:error] = "Incorrect Email or Password."
      render :new
    end
  end

  def destroy
  	logout
    flash[:success] = "You have been logged out Successfully."
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      flash[:success] = 'Welcome to DropShipping'
      redirect_to root_path
    else
      flash[:error] = "Please enter valid information."
      render :new
    end
  end

  private

  def user_params
	params.require(:user).permit(:name,:email,:password)
  end 	
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/categories/_form.html.erb
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-lg-10">
			<div class="card">
				<div class="card-body">
					<div class="form-validation">
						<%= render partial: 'partials/shared/form_errors', locals: {:object => category} %>
						<h3> Category Information </h3>
						<hr>
						<br><br>
						<%= form_with(model: [:admin,category],html:{'data-parsley-validate':true} , local: true) do |form| %>
						
						<div class="form-group row">
							<label class="col-lg-4 text-right col-form-label"> Name <span class="text-danger">*</span></label>
							<div class="col-lg-4">
								<%= form.text_field :name , class: 'form-control input-default', 'data-parsley-trigger':"change" ,'required':'true' %>
							</div>
						</div>

						<div class="form-group row">
							<label class="col-lg-4 text-right col-form-label"> Parent Category ID <span class="text-danger">*</span></label>
							<div class="col-lg-4">
								<%= form.number_field :parent_id , class: 'form-control input-default', 'data-parsley-trigger':"change" %>
								<p> Leave blank if root </p>
							</div>
						</div>
					

						<div class="form-group row">
							<div class="col-lg-8 ml-auto">
								<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</div>

						<% end %>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/categories/edit.html.erb
<%= render partial: 'partials/shared/breadcrums_with_title' %>

<%= render 'form', category: @category %>

app/views/admin/categories/index.html.erb
<%= render partial: 'partials/shared/breadcrums_with_title' %>

<div class='row'>
	<div class='col-lg-10 offset-lg-9'>
		<%= link_to 'Create Category', new_admin_category_path, class: 'btn btn-primary' %>
	</div>
</div>  

<br>

<div class="row">

	<div class="col-lg-10 offset-lg-1 dataTables_wrapper no-footer">
		<%= datagrid_form_for @categories_grid, url: admin_categories_path %>

		<%= datagrid_table(@categories_grid) %>
		<div style="margin-top:10px" class="row"> 
			<div class="col-lg-2" style="margin-top:10px">
				Showing <%= @categories_grid.assets.count %> of <%= @categories_grid.assets.total_count %>
			</div>
			<div class="col-lg-10">
				<%= paginate @categories_grid.assets %>
			</div>
		</div>
		<br>
	</div> 
</div>

app/views/admin/categories/new.html.erb
<%= render partial: 'partials/shared/breadcrums_with_title' %>

<%= render 'form', category: @category %>

app/views/admin/companies/_form.html.erb
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-lg-10">
			<div class="card">
				<div class="card-body">
					<div class="form-validation">
						<%= render partial: 'partials/shared/form_errors', locals: {:object => company} %>
						<h3> Company Information </h3>
						<hr>
						<br><br>
						<%= form_with(model: [:admin,company],html:{'data-parsley-validate':true} , local: true) do |form| %>
						
						<div class="form-group row">
							<label class="col-lg-4 text-right col-form-label"> Name <span class="text-danger">*</span></label>
							<div class="col-lg-4">
								<%= form.text_field :name , class: 'form-control input-default', 'data-parsley-trigger':"change" ,'required':'true' %>
							</div>
						</div>

						<div class="form-group row">
							<label class="col-lg-4 text-right col-form-label"> Owner ID <span class="text-danger">*</span></label>
							<div class="col-lg-4">
								<%= form.number_field :owner_id , class: 'form-control input-default', 'data-parsley-trigger':"change" ,'required':'true' %>
							</div>
						</div>


						<div class="form-group row">
							<label class="col-lg-4 text-right col-form-label">Type <span class="text-danger">*</span></label>
							<div class="col-lg-4">
								<%= form.select :company_type , Company::TYPE.invert , {include_blank:'Select Type'}, {class:'form-control input-default','data-parsley-trigger':"change" ,'required':'true' } %>
							</div>
						</div>

						<div class="form-group row">
							<label class="col-lg-4 text-right col-form-label">Status <span class="text-danger">*</span></label>
							<div class="col-lg-4">
								<%= form.select :status , Company::STATUS.invert , {include_blank:'Select Status'}, {class:'form-control input-default','data-parsley-trigger':"change" ,'required':'true' } %>
							</div>
						</div>
						

						<div class="form-group row">
							<label class="col-lg-4 text-right col-form-label">City <span class="text-danger">*</span></label>
							<div class="col-lg-4">
								<%= form.select :city_id , City.all.map {|city| [city.name,city.id] }, {include_blank:'Select City'}, {class:'form-control input-default','data-parsley-trigger':"change" ,'required':'true' } %>
							</div>
						</div>

						<div class="form-group row">
							<label class="col-lg-4 text-right col-form-label"> Address <span class="text-danger">*</span></label>
							<div class="col-lg-4">
								<%= form.text_area :address , size: "40x6" , style: 'height:80px' ,class: 'form-control input-default', 'data-parsley-trigger':"change" ,'required':'true' %>
							</div>
						</div>


						<div class="form-group row">
							<div class="col-lg-8 ml-auto">
								<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</div>

						<% end %>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/companies/edit.html.erb
<h1>Update Company</h1>

<%= render partial: 'partials/shared/breadcrums_with_title' %>

<%= render 'form', company: @company %>

app/views/admin/companies/index.html.erb
<%= render partial: 'partials/shared/breadcrums_with_title' %>

<div class='row'>
	<div class='col-lg-10 offset-lg-9'>
		<%= link_to 'Create Company', new_admin_company_path, class: 'btn btn-primary' %>
	</div>
</div>  

<br>

<div class="row">

	<div class="col-lg-10 offset-lg-1 dataTables_wrapper no-footer">
		<%= datagrid_form_for @companies_grid, url: admin_companies_path %>

		<%= datagrid_table(@companies_grid) %>
		<div style="margin-top:10px" class="row"> 
			<div class="col-lg-2" style="margin-top:10px">
				Showing <%= @companies_grid.assets.count %> of <%= @companies_grid.assets.total_count %>
			</div>
			<div class="col-lg-10">
				<%= paginate @companies_grid.assets %>
			</div>
		</div>
		<br>
	</div> 
</div>

app/views/admin/companies/new.html.erb
<%= render partial: 'partials/shared/breadcrums_with_title' %>

<%= render 'form', company: @company %>

app/views/users/new.html.erb
    <div id="main-wrapper">

        <div class="unix-login">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-lg-4">
                        <div class="login-content card">
                            <div class="login-form">
                                <h4>Register with DropShipping</h4>
                                <%= form_for @user do |f| %>
                                    <div class="form-group">
                                        <label>Name</label>
                                        <%= f.text_field :name , class: 'form-control', placeholder: 'Name' %>
                                    </div>
                                    <div class="form-group">
                                        <label>Email address</label>
                                        <%= f.text_field :email , class: 'form-control', placeholder: 'Email' %>
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <%= f.password_field :password , class: 'form-control' %>
                                    </div>

                                    <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Register</button>
                                    <div class="register-link m-t-15 text-center">
                                        <p>Already have account ? <%= link_to 'Sign In', new_session_path %></p>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>