config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root to: 'main#index'

  get 'main/index'

  resources :design_reference, only: [:index] do
  	collection do
  	  get :register
    end
  end

  resources :users, only: [:create,:update] 
  get 'signup' => 'users#new', as: :new_user	

  resources :sessions, only: [:create]
  get 'logout' => 'sessions#destroy' 
  get 'login'  => 'sessions#new', as: :new_session

  resources :admin, only: [:index]

  namespace :admin do
    resources :companies
    resources :categories
  end  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user.roles.includes(:permissions).each do |role|
        role.permissions.each do |p|
            can p.action.to_sym, p.klass.constantize, p.condition_hash
        end
        can :manage, :all if role.super_admin?
    end    

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	extend ActsAsTree::TreeView
	acts_as_tree order: 'name'

	extend FriendlyId
    friendly_id :name, use: :slugged

end

app/models/city.rb
class City < ApplicationRecord

	validates :name, :slug , presence: true
	
end

app/models/company.rb
class Company < ApplicationRecord
	extend FriendlyId
	friendly_id :uid, use: :slugged
	attr_accessor :slug

	belongs_to :city

	validates :name, :owner_id , :city_id, :address ,presence: true

	TYPE = { 1 => 'Seller' , 2 => 'Vendor' }
	STATUS = { 1 => 'Active' , 2 => 'InActive', 3 => 'Blocked' }

end

app/models/permission.rb
class Permission < ApplicationRecord

	has_and_belongs_to_many :roles

	serialize :condition , Hash
	
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
	has_and_belongs_to_many :permissions

	def super_admin?
	  uid == 'super_admin'
	end
	
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  delegate :can?, :cannot?, :to => :ability

  has_and_belongs_to_many :roles

  def ability
    @ability ||= Ability.new(self)
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :require_login
	authorize_resource
	layout 'admin'
	before_action :set_crumb

	def index
	end	

	def set_crumb
    	add_crumb "Admin", admin_index_path
	end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	rescue_from CanCan::AccessDenied do |exception|
		redirect_to main_app.root_url, :alert => exception.message
	end
	
end

app/controllers/design_reference_controller.rb
class DesignReferenceController < ApplicationController
  
  def index
  end

  def register
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
  end

  def create
  	user = login(params[:email], params[:password], true)
    if user.present?
      flash[:success] = "Signed In Successfully"
      redirect_back_or_to root_url
    else
      flash[:error] = "Incorrect Email or Password."
      render :new
    end
  end

  def destroy
  	logout
    flash[:success] = "You have been logged out Successfully."
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      flash[:success] = 'Welcome to DropShipping'
      redirect_to root_path
    else
      flash[:error] = "Please enter valid information."
      render :new
    end
  end

  private

  def user_params
	params.require(:user).permit(:name,:email,:password)
  end 	
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/datagrid/_enum_checkboxes.html.erb
<%# 
Indent in this file may cause extra space to appear.
You can add indent if whitespace doesn't matter for you
%>
<%- elements.each do |value, text, checked| -%>
<%- id = [form.object_name, filter.name, value].join('_').underscore -%>
<%= form.label filter.name, options.merge(:for => id) do -%>
<%= form.check_box(filter.name, {:multiple => true, :id => id, :checked => checked, :include_hidden => false}, value.to_s, nil) -%>
<%= text -%>
<%- end -%>
<%- end -%>

app/views/datagrid/_form.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <button type="button" class="btn btn-primary btn-addon m-b-10" data-toggle="collapse" data-target="#filters" aria-expanded="false" aria-controls="filters">Filters<i class="ti-search" style="margin-left:10px"></i></button>
  </button>
  <div class="collapse" id="filters">
    <div class="card card-body">
      <%= form_for grid, options do |f| -%>
      <% grid.filters.each_with_index do |filter,i| %>
      <div class="datagrid-filter filter form-group row">
        <%= f.datagrid_label filter,  {class: 'col-lg-4 text-right col-form-label'}  %>
        <%= f.datagrid_filter filter, {class: 'col-lg-4 input-default form-control'} %>
      </div>
      <% end %>
      <div class="datagrid-actions offset-lg-9">
        <%= f.submit 'Apply', :class => "datagrid-submit btn btn-primary" %>
        <%# https://github.com/rails/rails/pull/14949 -%>
        <% empty_parameter = Rails.version >= "4.1.0" && Rails.version <= '4.1.2' ? nil : {}-%>
        <%= link_to raw('<i class="ti-close" style="margin-right:5px"></i>Clear All'), url_for(grid.to_param => empty_parameter), :class => "datagrid-reset btn btn-danger btn-flat btn-addon" %>
      </div>
      <% end -%>
    </div>
  </div>
</div></div>  

app/views/datagrid/_head.html.erb
<tr>
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <th class="<%= datagrid_column_classes(grid, column) %>">
      <%= column.header %>
      <%= datagrid_order_for(grid, column, options) if column.supports_order? && options[:order]%>
    </th>
  <% end %>
</tr>

app/views/datagrid/_order_for.html.erb
<span class="order">
  <%= link_to(
      I18n.t("datagrid.table.order.asc").html_safe,
      datagrid_order_path(grid, column, false),
      :class => "asc") %>
  <%= link_to(
      I18n.t("datagrid.table.order.desc").html_safe,
      datagrid_order_path(grid, column, true),
      :class => "desc") %>
</span>

app/views/datagrid/_range_filter.html.erb
<%= form.text_field(filter.name, from_options) %>
<span class="separator <%= filter.type %>"> - </span>
<%= form.text_field(filter.name, to_options) %>

app/views/datagrid/_row.html.erb
<tr>
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <td class="<%= datagrid_column_classes(grid, column) %>"><%= datagrid_value(grid, column, asset) %></td>
  <% end %>
</tr>

app/views/datagrid/_table.html.erb
<%#
Local variables:
* grid - instance of Datagrid
* assets - Array of database Entities
* options - passed options Hash
%>
<% if grid.html_columns(*options[:columns]).any? %>
  <%= content_tag :table, options[:html].merge(class: "display nowrap table table-hover table-striped table-bordered dataTable") do %>
    <thead>
      <%= datagrid_header(grid, options) %>
    </thead>
    <tbody>
      <% if assets.any? %>
        <%= datagrid_rows(grid, assets, options) %>
      <% else %>
        <tr><td class="noresults" colspan="100%"><%= I18n.t('datagrid.no_results').html_safe %></td></tr>
      <% end %>
    </tbody>
  <% end %>
<% else -%>
  <%= I18n.t("datagrid.table.no_columns").html_safe %>
<% end %>

app/views/layouts/_admin_navbar.html.erb
<div class="header">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">
                <b><img src="<%=image_path('logo.png')%>" alt="homepage" class="dark-logo" /></b>
                <span><img src="<%=image_path('logo-text.png')%>" alt="homepage" class="dark-logo" /></span>
            </a>
        </div>
        <div class="navbar-collapse">
            <ul class="navbar-nav mr-auto mt-md-0">
                <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted  " href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted  " href="javascript:void(0)">
                    <li class="nav-item dropdown mega-dropdown"> <a class="nav-link dropdown-toggle text-muted  " href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-th-large"></i>                <div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
                    </a>
                    <div class="dropdown-menu">
                        <ul class="mega-dropdown-menu row">

                            <li class="col-lg-6 col-xlg-3 m-b-30">
                                <ul class="list-style-none">
                                    <li><%= link_to raw('<i class="fa fa-square"></i> Company Managment'), admin_companies_path %></li>
                                    <li><%= link_to raw('<i class="fa fa-square"></i> Category Managment'), admin_categories_path %></li>
                                </ul>
                            </li>
                            <li class="col-lg-6 col-xlg-3 m-b-30">
                                
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DropShipping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

 </head>

  <body class="fix-header fix-sidebar">
  	
    <%= render :partial => 'partials/shared/flash_messages' %>

    <%= render :partial => 'layouts/admin_navbar' %>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DropShipping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

 </head>

  <body class="fix-header fix-sidebar">
  	
    <%= render :partial => 'partials/shared/flash_messages' %>

    <%= yield %>

  </body>
</html>

app/views/partials/shared/_breadcrums_with_title.html.erb
            <div class="row page-titles">
                <div class="col-md-5 align-self-center">
                    <h3 class="text-primary"><%= @_crumbs.last[0] if @_crumbs.present? %></h3> </div>
                <div class="col-md-7 align-self-center">
                        <%= render_crumbs %>
                </div>
            </div>

app/views/partials/shared/_flash_messages.html.erb
<div class='container'>
	<% flash.each do |key, value| %>
	<% key = 'danger' if key == 'alert' || key == 'error' %>
	<% key = 'success'  if key == 'notice' %>
	<div class="alert alert-<%= key %> alert-dismissible fade show" style="margin-top:10px">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">×</span>
		</button>
		<%= value %>		
	</div>
	<% end %>
</div>

app/views/partials/shared/_form_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation" class="col-md-8">
      <ul>
      <% object.errors.full_messages.each do |message| %>
         <div class="alert alert-danger alert-dismissible fade show"><%= message %>
         	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
         </div>
      <% end %>
      </ul>
    </div>
  <% end %>